apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: archive-location-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: argoproj/argosay:v2
      command: [cowsay]
      args: ["hello world"]
    # archiveLocation allows configuring the archive location for a specific step
    archiveLocation:
      archiveLogs: true
